{
  "actor": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "created_at": "2018-06-18T06:34:09Z",
  "event": "unlabeled",
  "id": 1685423112,
  "issue": {
    "body": "\r\n/kind bug\r\n\r\n\r\n\r\n**What happened**:\r\nkubelet fails after `kubeadm reset`\r\n\r\n**What you expected to happen**:\r\nI expect to be able to run `kubeadm init` again after `kubeadm reset`, but got failing kubelet healthcheck during `kubeadm init` \r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\nRun `kubeadm init`, then `kubectl drain master0 --delete-local-data=true --force --ignore-daemonsets`, then `kubeadm reset` and then `kubectl status kubelet`. \r\n\r\nIf I simply restart kubelet service, it goes back to starting state like it should be after first installation of kubelet if I undesrtand correctly. I think it's an easy fix, just to add `kubectl restart kubelet` to the end of `kubeadm reset` logic\r\n\r\n\r\n",
    "comments": 1,
    "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/65165/comments",
    "created_at": "2018-06-17T16:36:02Z",
    "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/65165/events",
    "html_url": "https://github.com/kubernetes/kubernetes/issues/65165",
    "id": 333075344,
    "labels": [
      {
        "color": "0052cc",
        "id": 451459590,
        "name": "area/kubeadm",
        "node_id": "MDU6TGFiZWw0NTE0NTk1OTA=",
        "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/area/kubeadm"
      },
      {
        "color": "e11d21",
        "id": 105146071,
        "name": "kind/bug",
        "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
        "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
      },
      {
        "color": "d2b48c",
        "id": 173494222,
        "name": "sig/cluster-lifecycle",
        "node_id": "MDU6TGFiZWwxNzM0OTQyMjI=",
        "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/cluster-lifecycle"
      }
    ],
    "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/65165/labels{/name}",
    "locked": false,
    "node_id": "MDU6SXNzdWUzMzMwNzUzNDQ=",
    "number": 65165,
    "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
    "state": "open",
    "title": "kubeadm reset leaves kubelet in failing state",
    "updated_at": "2018-06-18T06:35:30Z",
    "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/65165",
    "user": {
      "avatar_url": "https://avatars2.githubusercontent.com/u/2006610?v=4",
      "events_url": "https://api.github.com/users/mlushpenko/events{/privacy}",
      "followers_url": "https://api.github.com/users/mlushpenko/followers",
      "following_url": "https://api.github.com/users/mlushpenko/following{/other_user}",
      "gists_url": "https://api.github.com/users/mlushpenko/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/mlushpenko",
      "id": 2006610,
      "login": "mlushpenko",
      "organizations_url": "https://api.github.com/users/mlushpenko/orgs",
      "received_events_url": "https://api.github.com/users/mlushpenko/received_events",
      "repos_url": "https://api.github.com/users/mlushpenko/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/mlushpenko/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mlushpenko/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/mlushpenko"
    }
  },
  "label": {
    "color": "ededed",
    "name": "needs-sig"
  },
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/events/1685423112"
}